# Rubocop overrides, double quotes, and more provided by
# the testdouble/standard gem
# ref: https://github.com/testdouble/standard
# ref: https://github.com/rubocop/rubocop/blob/master/config/default.yml

require:
  - standard
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Rails/FilePath:
  EnforcedStyle: arguments

Rails/UnknownEnv:
  Enabled: false

# Ref: https://github.com/rubocop/rubocop-rspec/issues/210
RSpec/ExampleLength:
  CountAsOne:
    - heredoc
  Max: 11

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - node_modules/**/*
    - public/**/*
    - vendor/**/*
    - coverage/**/*

Rails:
  Enabled: true # enable rubocop-rails cops
RSpec:
  Enabled: true # enable rubocop-rspec cops
RSpec/DescribeClass:
  Enabled: false
