require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_profile/professionals" do
  describe "GET /show" do
    let(:user) { create(:user) }

    before do
      # https://stackoverflow.com/questions/10121835/how-do-i-simulate-a-login-with-rspec
      # https://stackoverflow.com/questions/27284657/undefined-method-env-for-nilnilclass-in-setup-controller-for-warden-error
      login_as user
    end

    it "renders a successful response" do
      get user_profile_professional_url(user.professional_profile)
      expect(response).to be_successful
    end
  end
end
