require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/founder/firms" do
  # This should return the minimal set of attributes required to create a valid
  # Founder::Firm. As you add validations to Founder::Firm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }
  let(:user) { create(:user) }

  around do |ex|
    # https://stackoverflow.com/questions/10121835/how-do-i-simulate-a-login-with-rspec
    # https://stackoverflow.com/questions/27284657/undefined-method-env-for-nilnilclass-in-setup-controller-for-warden-error
    # https://rubydoc.info/gems/rspec-core/RSpec%2FCore%2FHooks:around
    login_as user
    ex.run
    logout
  end

  describe "GET /index" do
    it "renders a successful response" do
      Founder::Firm.create! valid_attributes
      get founder_firms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      firm = Founder::Firm.create! valid_attributes
      get founder_firm_url(firm)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_founder_firm_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      firm = Founder::Firm.create! valid_attributes
      get edit_founder_firm_url(firm)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Founder::Firm" do
        expect {
          post founder_firms_url, params: { founder_firm: valid_attributes }
        }.to change(Founder::Firm, :count).by(1)
      end

      it "redirects to the created founder_firm" do
        post founder_firms_url, params: { founder_firm: valid_attributes }
        expect(response).to redirect_to(founder_firm_url(Founder::Firm.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Founder::Firm" do
        expect {
          post founder_firms_url, params: { founder_firm: invalid_attributes }
        }.not_to change(Founder::Firm, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post founder_firms_url, params: { founder_firm: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested founder_firm" do
        firm = Founder::Firm.create! valid_attributes
        patch founder_firm_url(firm), params: { founder_firm: new_attributes }
        firm.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the founder_firm" do
        firm = Founder::Firm.create! valid_attributes
        patch founder_firm_url(firm), params: { founder_firm: new_attributes }
        firm.reload
        expect(response).to redirect_to(founder_firm_url(firm))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        firm = Founder::Firm.create! valid_attributes
        patch founder_firm_url(firm), params: { founder_firm: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested founder_firm" do
      firm = Founder::Firm.create! valid_attributes
      expect {
        delete founder_firm_url(firm)
      }.to change(Founder::Firm, :count).by(-1)
    end

    it "redirects to the founder_firms list" do
      firm = Founder::Firm.create! valid_attributes
      delete founder_firm_url(firm)
      expect(response).to redirect_to(founder_firms_url)
    end
  end
end
