require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/physical_locations" do
  # This should return the minimal set of attributes required to create a valid
  # PhysicalLocation. As you add validations to PhysicalLocation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PhysicalLocation.create! valid_attributes
      get physical_locations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      physical_location = PhysicalLocation.create! valid_attributes
      get physical_location_url(physical_location)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      physical_location = PhysicalLocation.create! valid_attributes
      get edit_physical_location_url(physical_location)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PhysicalLocation" do
        expect {
          post physical_locations_url, params: { physical_location: valid_attributes }
        }.to change(PhysicalLocation, :count).by(1)
      end

      it "redirects to the created physical_location" do
        post physical_locations_url, params: { physical_location: valid_attributes }
        expect(response).to redirect_to(physical_location_url(PhysicalLocation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PhysicalLocation" do
        expect {
          post physical_locations_url, params: { physical_location: invalid_attributes }
        }.not_to change(PhysicalLocation, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post physical_locations_url, params: { physical_location: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested physical_location" do
        physical_location = PhysicalLocation.create! valid_attributes
        patch physical_location_url(physical_location), params: { physical_location: new_attributes }
        physical_location.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the physical_location" do
        physical_location = PhysicalLocation.create! valid_attributes
        patch physical_location_url(physical_location), params: { physical_location: new_attributes }
        physical_location.reload
        expect(response).to redirect_to(physical_location_url(physical_location))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        physical_location = PhysicalLocation.create! valid_attributes
        patch physical_location_url(physical_location), params: { physical_location: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested physical_location" do
      physical_location = PhysicalLocation.create! valid_attributes
      expect {
        delete physical_location_url(physical_location)
      }.to change(PhysicalLocation, :count).by(-1)
    end

    it "redirects to the physical_locations list" do
      physical_location = PhysicalLocation.create! valid_attributes
      delete physical_location_url(physical_location)
      expect(response).to redirect_to(physical_locations_url)
    end
  end
end
