development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: relaunch_community_development

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>/<%= ENV['REDIS_DATABASE'] %>
  channel_prefix: relaunch_community_staging
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>/<%= ENV['REDIS_DATABASE'] %>
  channel_prefix: relaunch_community_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
